### ISSUE TITLE
Problem when running gaussian-process-kernel-fitting.ipynb

### ISSUE THREAD

**Issue by malsioufi** [peterroelants/peterroelants.github.io#20]
Thank you very much for the great repo!
When I try to run the code in the notebook "gaussian-process-kernel-fitting.ipynb" in the "Tuning the hyperparameters" section I get the exception 
"RuntimeError: `loss` passed to Optimizer.compute_gradients should be a function when eager execution is enabled."

It seems to be related to tensorflow version, but I could not solve it myself.
I tried the solution mention here:
https://stackoverflow.com/questions/57858219/loss-passed-to-optimizer-compute-gradients-should-be-a-function-when-eager-exe
However, that creates another problem. 

my evironment is running under:
python 3.6.9
tensorflow==2.1.0
tensorflow-estimator==2.1.0
tensorflow-probability==0.9.0

**Comment by peterroelants** [comment]
Regarding backward compatibility, the state of TensorFlow is a bit of a
mess since the switch to 2.0. The easiest way would be to run the notebook
in an environment with exactly the same versions as are printed at the
bottom of the notebook.

I haven't spent time upgrading the code to 2.0. However, if you want to get
it to work on 2.0 I would recommend to  look at this post which seems to
deal with the same issue of using the TF probability Gaussian Process
module in TF 2.0: https://stackoverflow.com/q/58044469/919431
